
package javaapplicationejemplob;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolaMundoWebService", targetNamespace = "http://ws.java.curso.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolaMundoWebService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.java.curso.edu/", className = "javaapplicationejemplob.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.java.curso.edu/", className = "javaapplicationejemplob.HelloResponse")
    @Action(input = "http://ws.java.curso.edu/HolaMundoWebService/helloRequest", output = "http://ws.java.curso.edu/HolaMundoWebService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param num1
     * @param num2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://ws.java.curso.edu/", className = "javaapplicationejemplob.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://ws.java.curso.edu/", className = "javaapplicationejemplob.SumarResponse")
    @Action(input = "http://ws.java.curso.edu/HolaMundoWebService/sumarRequest", output = "http://ws.java.curso.edu/HolaMundoWebService/sumarResponse")
    public double sumar(
        @WebParam(name = "num1", targetNamespace = "")
        double num1,
        @WebParam(name = "num2", targetNamespace = "")
        double num2);

}
